import { createContext, useContext, useState, useEffect } from "react";

export type Lang = "en" | "ar";

const translations = {
  en: {
    nav: {
      dashboard: "Dashboard",
      brands: "Brands",
      studio: "Creative Studio",
      library: "Library",
      pricing: "Pricing",
      navigation: "Navigation",
    },
    layout: {
      appName: "AdCreative",
      aiPlatform: "AI Platform",
      signOut: "Sign Out",
      signingOut: "Signing out…",
      profile: "Profile",
      upgradeToPro: "Upgrade to Pro",
      freePlan: "Free Plan",
      proPlan: "Pro Plan",
      businessPlan: "Business Plan",
    },
    dashboard: {
      poweredBy: "Powered by Gemini AI",
      welcomeBack: "Welcome back, {name}! 👋",
      heroSubtitle: "Create stunning, conversion-focused ad creatives in seconds. Let AI handle the design while you focus on growth.",
      generateCreative: "Generate Creative",
      manageBrands: "Manage Brands",
      totalBrands: "Total Brands",
      creativesMade: "Creatives Made",
      readyToUse: "Ready to Use",
      favorites: "Favorites",
      quickActions: "Quick Actions",
      generateNew: "Generate New Creative",
      generateNewDesc: "AI-powered ad creation",
      addBrand: "Add a Brand",
      addBrandDesc: "Setup brand colors & fonts",
      browseLibrary: "Browse Library",
      browseLibraryDesc: "View all your creatives",
      platformUsage: "Platform Usage",
      noDataYet: "No data yet. Generate your first creative!",
      yourBrands: "Your Brands",
      viewAll: "View all",
      recentCreatives: "Recent Creatives",
      viewAll2: "View All",
      noCreativesYet: "No creatives yet",
      noCreativesDesc: "Generate your first AI-powered ad creative and it will appear here.",
      createFirstAd: "Create First Ad",
      generating: "Generating…",
      whatYouCanCreate: "What You Can Create",
      gettingStarted: "Getting Started",
      createAccount: "Create an account",
      setupBrand: "Set up your first brand",
      generateFirst: "Generate your first creative",
      downloadPublish: "Download and publish your ad",
    },
    brands: {
      title: "Brand Management",
      subtitle: "Manage your brand kits for on-brand AI generation.",
      addBrand: "Add Brand",
      createBrandKit: "Create Brand Kit",
      brandName: "Brand Name",
      brandNameRequired: "Brand name is required",
      industry: "Industry",
      typography: "Typography",
      primaryColor: "Primary Color",
      secondaryColor: "Secondary Color",
      website: "Website",
      optional: "(optional)",
      brandDescription: "Brand Description",
      preview: "Preview",
      cancel: "Cancel",
      saveBrand: "Save Brand",
      noBrandsYet: "No brands yet",
      noBrandsDesc: "Create your first brand kit to start generating on-brand AI creatives.",
      createFirstBrand: "Create First Brand",
      addNewBrand: "Add New Brand",
      addNewBrandDesc: "Set up brand colors, fonts & more",
      generateCreative: "Generate Creative",
      brandCreated: "Brand created!",
      brandCreatedDesc: "{name} is ready for creative generation.",
      brandDeleted: "Brand deleted",
      failedCreate: "Failed to create brand",
      failedDelete: "Failed to delete brand",
      deleteConfirm: 'Delete "{name}"? This will also delete all creatives for this brand.',
    },
    studio: {
      title: "Generate Your Ad Creative",
      subtitle: "Three simple steps. Powered by Gemini AI.",
      step1: "Brand & Format",
      step2: "Product Details",
      step3: "Result",
      selectBrand: "Select Your Brand",
      selectFormat: "Select Ad Format",
      noBrandsYet: "No brands yet",
      noBrandsDesc: "Create a brand first before generating creatives.",
      addBrand: "Add Brand",
      pickOne: "← pick one",
      continueBtn: "Continue",
      describeProduct: "Describe Your Product",
      creativeTitle: "Creative Title",
      creativeTitleHint: "(optional — auto-generated if blank)",
      productName: "Product / Service Name",
      campaignGoal: "Campaign Goal",
      productDesc: "Product Description & Key Benefits",
      targetAudience: "Target Audience",
      targetAudienceHint: "(optional)",
      backBtn: "Back",
      generateBtn: "Generate Creative",
      generateVideoBtn: "Generate AI Video",
      uploadVideoBtn: "Upload Video",
      starting: "Starting…",
      generatingTitle: "Gemini AI is crafting your creative",
      generatingSubtitle: "Analyzing brand, writing copy, generating image…",
      generatingVideoTitle: "AI is generating your video",
      generatingVideoSubtitle: "Creating script, voiceover, and video…",
      writingCopy: "Writing ad copy",
      generatingImage: "Generating image",
      generatingVideo: "Generating video",
      finalizing: "Finalizing creative",
      failed: "Generation Failed",
      failedDesc: "Something went wrong during generation. This may be a temporary issue with the AI service.",
      tryAgain: "Try Again",
      newCreative: "New Creative",
      downloadImage: "Download Image",
      downloadVideo: "Download Video",
      viewLibrary: "View Library",
      createAnother: "Create Another",
      headline: "Headline",
      bodyCopy: "Body Copy",
      callToAction: "Call to Action",
      performanceBreakdown: "Performance Breakdown",
      headlineImpact: "Headline Impact",
      copyCl: "Copy Clarity",
      ctaStrength: "CTA Strength",
      score: "Score",
      goals: {
        awareness: "🎯 Brand Awareness",
        traffic: "🚀 Drive Traffic",
        leads: "📋 Generate Leads",
        sales: "💰 Boost Sales",
        engagement: "❤️ Increase Engagement",
      },
      selectBrandAndFormat: "Select a brand and ad format to continue",
      selectBrandAndFormatDesc: "Choose a brand from the grid above, then pick an ad format.",
      selectBrandFirst: "Select a brand first",
      selectBrandFirstDesc: "Click one of the brand cards above to select it.",
      selectAdFormat: "Select an ad format",
      selectAdFormatDesc: "Choose a platform format (e.g. Instagram Post, Facebook Ad) below the brand section.",
      productNameRequired: "Product name is required",
      productNameRequiredDesc: "Enter the name of what you're advertising.",
      productDescRequired: "Product description is required",
      productDescRequiredDesc: "Describe your product's key benefits so the AI can write compelling copy.",
      generationFailed: "Generation failed",
      productNamePlaceholder: "What are you advertising?",
      productDescPlaceholder: "Describe main benefits, unique selling points, and why customers should choose this product...",
      targetAudiencePlaceholder: "e.g. Millennials aged 25–35 interested in fitness and wellness",
      mediaType: "Media Type",
      image: "Image",
      video: "Video",
      uploadVideo: "Upload Video",
      generateAiVideo: "AI Generate Video",
      uploadVideoDesc: "Upload your own video file (MP4, WebM, MOV)",
      generateAiVideoDesc: "Let AI create a video creative for you",
      videoFile: "Video File",
      dragDropVideo: "Drag & drop your video or click to browse",
      videoFormats: "MP4, WebM, MOV — max 100MB",
      uploadingVideo: "Uploading…",
      videoUploaded: "Video uploaded successfully",
      proFeature: "Pro Feature",
      proFeatureDesc: "Video generation requires a Pro or Business plan.",
      upgradeToPro: "Upgrade to Pro",
    },
    library: {
      title: "Creative Library",
      subtitle: "Manage, download, and organize all your AI-generated assets.",
      search: "Search creatives by title...",
      allBrands: "All Brands",
      allPlatforms: "All Platforms",
      allTypes: "All Types",
      images: "Images",
      videos: "Videos",
      noCreatives: "No creatives found",
      noCreativesDesc: "Adjust your filters or generate a new creative in the studio.",
      download: "Download",
      generating: "Generating...",
      score: "Score",
      deleteConfirm: "Delete this creative?",
      videoCreative: "Video Creative",
      playVideo: "Play video",
    },
    pricing: {
      title: "Simple, Transparent Pricing",
      subtitle: "Choose the plan that fits your needs. Start free, scale as you grow.",
      monthly: "Monthly",
      yearly: "Yearly",
      savePercent: "Save 20%",
      mostPopular: "Most Popular",
      currentPlan: "Current Plan",
      getStarted: "Get Started Free",
      upgradePro: "Upgrade to Pro",
      upgradeBtn: "Upgrade Now",
      contactSales: "Contact Sales",
      perMonth: "/month",
      perYear: "/year",
      billedYearly: "billed yearly",
      free: "Free",
      pro: "Pro",
      business: "Business",
      freeDesc: "Perfect for trying out AdCreative AI",
      proDesc: "For growing businesses and marketers",
      businessDesc: "For agencies and large teams",
      freePrice: "$0",
      proPrice: "$7",
      businessPrice: "$14",
      features: "Features",
      freePlanFeatures: [
        "5 AI-generated creatives/month",
        "2 brand kits",
        "Image creatives only",
        "Basic ad formats",
        "Performance scoring",
        "Download in PNG/JPG",
      ],
      proPlanFeatures: [
        "100 AI-generated creatives/month",
        "20 brand kits",
        "Image & video creatives",
        "AI video generation",
        "Video upload support",
        "All ad formats",
        "Priority AI generation",
        "Advanced performance analytics",
        "Download in all formats",
      ],
      businessPlanFeatures: [
        "Unlimited creatives",
        "Unlimited brand kits",
        "Image & video creatives",
        "AI video generation",
        "Team collaboration",
        "White-label exports",
        "API access",
        "Dedicated account manager",
        "Custom integrations",
        "SLA guarantee",
      ],
      faq: "Frequently Asked Questions",
      faqItems: [
        { q: "Can I change my plan later?", a: "Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately." },
        { q: "What counts as a 'creative'?", a: "Each AI-generated image or video counts as one creative. Downloading or duplicating does not use additional credits." },
        { q: "Do unused creatives roll over?", a: "Monthly credits reset each billing cycle and do not roll over." },
        { q: "Is there a free trial for Pro?", a: "You can start with our Free plan and upgrade anytime. We offer a 14-day money-back guarantee on paid plans." },
      ],
      comingSoon: "Stripe payments coming soon. Contact us to upgrade.",
    },
    login: {
      welcomeBack: "Welcome back",
      signInDesc: "Sign in to your account to continue.",
      getStarted: "Get started free",
      createAccountDesc: "Create your account and start generating ads.",
      signIn: "Sign In",
      createAccount: "Create Account",
      email: "Email",
      password: "Password",
      minPassword: "Min. 6 characters",
      name: "Full Name",
      namePlaceholder: "John Smith",
      confirmPassword: "Confirm Password",
      repeatPassword: "Repeat password",
      loginFailed: "Login failed",
      invalidCredentials: "Invalid email or password",
      registerFailed: "Registration failed",
      couldNotCreate: "Could not create account",
      signInBtn: "Sign In",
      createFreeAccount: "Create Free Account",
      noAccount: "Don't have an account?",
      createOne: "Create one free",
      alreadyHave: "Already have an account?",
      signInLink: "Sign in",
      aiPowered: "AI-Powered Creatives",
      aiPoweredDesc: "Generate stunning ads in seconds with Gemini AI",
      multiPlatform: "Multi-Platform Ready",
      multiPlatformDesc: "Facebook, Instagram, Google, TikTok & more",
      performance: "Performance Scores",
      performanceDesc: "Know which creatives will convert before you launch",
      joinMarketers: "Join 10,000+ marketers",
      generatingEveryday: "generating ads every day",
      createsActuallyConvert: "Create Ad Creatives",
      thatConvert: "That Actually Convert",
      aiTrusted: "AI-powered advertising platform trusted by thousands of marketers worldwide.",
    },
    common: {
      loading: "Loading your workspace…",
      go: "Go",
      failed: "Failed",
    },
  },
  ar: {
    nav: {
      dashboard: "لوحة التحكم",
      brands: "العلامات التجارية",
      studio: "استوديو الإبداع",
      library: "المكتبة",
      pricing: "الأسعار",
      navigation: "التنقل",
    },
    layout: {
      appName: "AdCreative",
      aiPlatform: "منصة الذكاء الاصطناعي",
      signOut: "تسجيل الخروج",
      signingOut: "جارٍ الخروج…",
      profile: "الملف الشخصي",
      upgradeToPro: "ترقية إلى Pro",
      freePlan: "الخطة المجانية",
      proPlan: "الخطة الاحترافية",
      businessPlan: "خطة الأعمال",
    },
    dashboard: {
      poweredBy: "مدعوم بـ Gemini AI",
      welcomeBack: "أهلاً بعودتك، {name}! 👋",
      heroSubtitle: "أنشئ إعلانات مذهلة وفعّالة في ثوانٍ. دع الذكاء الاصطناعي يتولى التصميم بينما تركز أنت على النمو.",
      generateCreative: "إنشاء إعلان",
      manageBrands: "إدارة العلامات التجارية",
      totalBrands: "إجمالي العلامات",
      creativesMade: "الإعلانات المنشأة",
      readyToUse: "جاهزة للاستخدام",
      favorites: "المفضلة",
      quickActions: "إجراءات سريعة",
      generateNew: "إنشاء إعلان جديد",
      generateNewDesc: "إنشاء إعلانات بالذكاء الاصطناعي",
      addBrand: "إضافة علامة تجارية",
      addBrandDesc: "إعداد الألوان والخطوط",
      browseLibrary: "تصفح المكتبة",
      browseLibraryDesc: "عرض جميع إعلاناتك",
      platformUsage: "استخدام المنصات",
      noDataYet: "لا توجد بيانات بعد. أنشئ إعلانك الأول!",
      yourBrands: "علاماتك التجارية",
      viewAll: "عرض الكل",
      recentCreatives: "الإعلانات الأخيرة",
      viewAll2: "عرض الكل",
      noCreativesYet: "لا توجد إعلانات بعد",
      noCreativesDesc: "أنشئ إعلانك الأول بالذكاء الاصطناعي وسيظهر هنا.",
      createFirstAd: "إنشاء أول إعلان",
      generating: "جارٍ الإنشاء…",
      whatYouCanCreate: "ما يمكنك إنشاؤه",
      gettingStarted: "البدء",
      createAccount: "إنشاء حساب",
      setupBrand: "إعداد علامتك التجارية الأولى",
      generateFirst: "إنشاء إعلانك الأول",
      downloadPublish: "تحميل ونشر إعلانك",
    },
    brands: {
      title: "إدارة العلامات التجارية",
      subtitle: "أدر مجموعات علامتك التجارية لإنشاء محتوى متناسق بالذكاء الاصطناعي.",
      addBrand: "إضافة علامة",
      createBrandKit: "إنشاء مجموعة العلامة التجارية",
      brandName: "اسم العلامة التجارية",
      brandNameRequired: "اسم العلامة التجارية مطلوب",
      industry: "الصناعة",
      typography: "الخطوط",
      primaryColor: "اللون الأساسي",
      secondaryColor: "اللون الثانوي",
      website: "الموقع الإلكتروني",
      optional: "(اختياري)",
      brandDescription: "وصف العلامة التجارية",
      preview: "معاينة",
      cancel: "إلغاء",
      saveBrand: "حفظ العلامة التجارية",
      noBrandsYet: "لا توجد علامات تجارية بعد",
      noBrandsDesc: "أنشئ أول مجموعة علامات تجارية لبدء إنشاء محتوى متناسق.",
      createFirstBrand: "إنشاء أول علامة تجارية",
      addNewBrand: "إضافة علامة جديدة",
      addNewBrandDesc: "إعداد الألوان والخطوط والمزيد",
      generateCreative: "إنشاء إعلان",
      brandCreated: "تم إنشاء العلامة التجارية!",
      brandCreatedDesc: "{name} جاهزة لإنشاء الإعلانات.",
      brandDeleted: "تم حذف العلامة التجارية",
      failedCreate: "فشل إنشاء العلامة التجارية",
      failedDelete: "فشل حذف العلامة التجارية",
      deleteConfirm: 'هل تريد حذف "{name}"؟ سيتم حذف جميع الإعلانات المرتبطة بها أيضاً.',
    },
    studio: {
      title: "أنشئ إعلانك الإبداعي",
      subtitle: "ثلاث خطوات بسيطة. مدعوم بـ Gemini AI.",
      step1: "العلامة والتنسيق",
      step2: "تفاصيل المنتج",
      step3: "النتيجة",
      selectBrand: "اختر علامتك التجارية",
      selectFormat: "اختر تنسيق الإعلان",
      noBrandsYet: "لا توجد علامات تجارية بعد",
      noBrandsDesc: "أنشئ علامة تجارية أولاً قبل إنشاء الإعلانات.",
      addBrand: "إضافة علامة",
      pickOne: "← اختر واحدة",
      continueBtn: "متابعة",
      describeProduct: "صف منتجك",
      creativeTitle: "عنوان الإعلان",
      creativeTitleHint: "(اختياري — يُنشأ تلقائياً إذا تُرك فارغاً)",
      productName: "اسم المنتج / الخدمة",
      campaignGoal: "هدف الحملة",
      productDesc: "وصف المنتج والمزايا الرئيسية",
      targetAudience: "الجمهور المستهدف",
      targetAudienceHint: "(اختياري)",
      backBtn: "رجوع",
      generateBtn: "إنشاء الإعلان",
      generateVideoBtn: "إنشاء فيديو بالذكاء الاصطناعي",
      uploadVideoBtn: "رفع فيديو",
      starting: "جارٍ البدء…",
      generatingTitle: "Gemini AI يصمم إعلانك",
      generatingSubtitle: "تحليل العلامة التجارية، كتابة النص، إنشاء الصورة…",
      generatingVideoTitle: "الذكاء الاصطناعي ينشئ الفيديو",
      generatingVideoSubtitle: "إنشاء السكريبت والتعليق الصوتي والفيديو…",
      writingCopy: "كتابة نص الإعلان",
      generatingImage: "إنشاء الصورة",
      generatingVideo: "إنشاء الفيديو",
      finalizing: "الإنهاء",
      failed: "فشل الإنشاء",
      failedDesc: "حدث خطأ أثناء الإنشاء. قد تكون هذه مشكلة مؤقتة في خدمة الذكاء الاصطناعي.",
      tryAgain: "حاول مجدداً",
      newCreative: "إعلان جديد",
      downloadImage: "تحميل الصورة",
      downloadVideo: "تحميل الفيديو",
      viewLibrary: "عرض المكتبة",
      createAnother: "إنشاء إعلان آخر",
      headline: "العنوان الرئيسي",
      bodyCopy: "نص الإعلان",
      callToAction: "دعوة للعمل",
      performanceBreakdown: "تحليل الأداء",
      headlineImpact: "تأثير العنوان",
      copyCl: "وضوح النص",
      ctaStrength: "قوة الدعوة للعمل",
      score: "النقاط",
      goals: {
        awareness: "🎯 الوعي بالعلامة التجارية",
        traffic: "🚀 زيادة الزيارات",
        leads: "📋 توليد العملاء المحتملين",
        sales: "💰 زيادة المبيعات",
        engagement: "❤️ زيادة التفاعل",
      },
      selectBrandAndFormat: "اختر علامة تجارية وتنسيق إعلان للمتابعة",
      selectBrandAndFormatDesc: "اختر علامة تجارية من الشبكة أعلاه، ثم اختر تنسيق إعلان.",
      selectBrandFirst: "اختر علامة تجارية أولاً",
      selectBrandFirstDesc: "انقر على إحدى بطاقات العلامات التجارية أعلاه.",
      selectAdFormat: "اختر تنسيق الإعلان",
      selectAdFormatDesc: "اختر تنسيق المنصة (مثل: منشور انستغرام، إعلان فيسبوك).",
      productNameRequired: "اسم المنتج مطلوب",
      productNameRequiredDesc: "أدخل اسم ما تُعلن عنه.",
      productDescRequired: "وصف المنتج مطلوب",
      productDescRequiredDesc: "صف مزايا منتجك الرئيسية حتى يتمكن الذكاء الاصطناعي من كتابة نص مقنع.",
      generationFailed: "فشل الإنشاء",
      productNamePlaceholder: "ما الذي تُعلن عنه؟",
      productDescPlaceholder: "صف المزايا الرئيسية ونقاط البيع الفريدة ولماذا يجب على العملاء اختيار هذا المنتج...",
      targetAudiencePlaceholder: "مثال: الشباب بين 25-35 سنة المهتمون بالصحة واللياقة",
      mediaType: "نوع الوسيط",
      image: "صورة",
      video: "فيديو",
      uploadVideo: "رفع فيديو",
      generateAiVideo: "إنشاء فيديو بالذكاء الاصطناعي",
      uploadVideoDesc: "ارفع ملف فيديو خاص بك (MP4, WebM, MOV)",
      generateAiVideoDesc: "دع الذكاء الاصطناعي ينشئ فيديو إعلاني لك",
      videoFile: "ملف الفيديو",
      dragDropVideo: "اسحب وأفلت الفيديو أو انقر للتصفح",
      videoFormats: "MP4, WebM, MOV — بحد أقصى 100MB",
      uploadingVideo: "جارٍ الرفع…",
      videoUploaded: "تم رفع الفيديو بنجاح",
      proFeature: "ميزة Pro",
      proFeatureDesc: "توليد الفيديو يتطلب خطة Pro أو Business.",
      upgradeToPro: "ترقية إلى Pro",
    },
    library: {
      title: "مكتبة الإعلانات",
      subtitle: "أدر وحمّل ونظّم جميع أصولك التي أنشأها الذكاء الاصطناعي.",
      search: "ابحث عن الإعلانات بالعنوان...",
      allBrands: "كل العلامات",
      allPlatforms: "كل المنصات",
      allTypes: "كل الأنواع",
      images: "صور",
      videos: "فيديوهات",
      noCreatives: "لم يتم العثور على إعلانات",
      noCreativesDesc: "عدّل الفلاتر أو أنشئ إعلاناً جديداً في الاستوديو.",
      download: "تحميل",
      generating: "جارٍ الإنشاء...",
      score: "النقاط",
      deleteConfirm: "هل تريد حذف هذا الإعلان؟",
      videoCreative: "إعلان فيديو",
      playVideo: "تشغيل الفيديو",
    },
    pricing: {
      title: "أسعار بسيطة وشفافة",
      subtitle: "اختر الخطة التي تناسبك. ابدأ مجاناً وتوسّع مع نموك.",
      monthly: "شهري",
      yearly: "سنوي",
      savePercent: "وفّر 20%",
      mostPopular: "الأكثر شيوعاً",
      currentPlan: "خطتك الحالية",
      getStarted: "ابدأ مجاناً",
      upgradePro: "ترقية إلى Pro",
      upgradeBtn: "ترقية الآن",
      contactSales: "تواصل مع المبيعات",
      perMonth: "/شهر",
      perYear: "/سنة",
      billedYearly: "يُفوتر سنوياً",
      free: "مجاني",
      pro: "Pro",
      business: "أعمال",
      freeDesc: "مثالي لتجربة AdCreative AI",
      proDesc: "للشركات المتنامية والمسوّقين",
      businessDesc: "للوكالات والفرق الكبيرة",
      freePrice: "$0",
      proPrice: "$7",
      businessPrice: "$14",
      features: "المميزات",
      freePlanFeatures: [
        "5 إعلانات بالذكاء الاصطناعي/شهر",
        "مجموعتان من العلامات التجارية",
        "إعلانات صور فقط",
        "تنسيقات إعلانات أساسية",
        "تقييم الأداء",
        "تحميل بصيغة PNG/JPG",
      ],
      proPlanFeatures: [
        "100 إعلان بالذكاء الاصطناعي/شهر",
        "20 مجموعة علامات تجارية",
        "إعلانات صور وفيديو",
        "توليد الفيديو بالذكاء الاصطناعي",
        "دعم رفع الفيديو",
        "جميع تنسيقات الإعلانات",
        "إنشاء ذكاء اصطناعي بأولوية",
        "تحليلات أداء متقدمة",
        "تحميل بجميع الصيغ",
      ],
      businessPlanFeatures: [
        "إعلانات غير محدودة",
        "مجموعات علامات تجارية غير محدودة",
        "إعلانات صور وفيديو",
        "توليد الفيديو بالذكاء الاصطناعي",
        "تعاون الفريق",
        "تصدير بالعلامة البيضاء",
        "وصول API",
        "مدير حساب مخصص",
        "تكاملات مخصصة",
        "ضمان SLA",
      ],
      faq: "الأسئلة الشائعة",
      faqItems: [
        { q: "هل يمكنني تغيير خطتي لاحقاً؟", a: "نعم، يمكنك الترقية أو التخفيض في أي وقت. تسري التغييرات فوراً." },
        { q: "ما الذي يُحتسب كـ 'إعلان'؟", a: "كل صورة أو فيديو يُنشأ بالذكاء الاصطناعي يُحسب كإعلان واحد. التحميل أو النسخ لا يستهلك رصيداً إضافياً." },
        { q: "هل تتراكم الإعلانات غير المستخدمة؟", a: "يتم إعادة تعيين الرصيد الشهري مع كل دورة فوترة ولا يتراكم." },
        { q: "هل هناك تجربة مجانية لـ Pro؟", a: "يمكنك البدء بخطتنا المجانية والترقية في أي وقت. نقدم ضماناً لاسترداد المال لمدة 14 يوماً على الخطط المدفوعة." },
      ],
      comingSoon: "مدفوعات Stripe قادمة قريباً. تواصل معنا للترقية.",
    },
    login: {
      welcomeBack: "أهلاً بعودتك",
      signInDesc: "سجّل دخولك للمتابعة.",
      getStarted: "ابدأ مجاناً",
      createAccountDesc: "أنشئ حسابك وابدأ إنشاء الإعلانات.",
      signIn: "تسجيل الدخول",
      createAccount: "إنشاء حساب",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      minPassword: "٦ أحرف على الأقل",
      name: "الاسم الكامل",
      namePlaceholder: "محمد أحمد",
      confirmPassword: "تأكيد كلمة المرور",
      repeatPassword: "أعد كلمة المرور",
      loginFailed: "فشل تسجيل الدخول",
      invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
      registerFailed: "فشل إنشاء الحساب",
      couldNotCreate: "تعذّر إنشاء الحساب",
      signInBtn: "تسجيل الدخول",
      createFreeAccount: "إنشاء حساب مجاني",
      noAccount: "ليس لديك حساب؟",
      createOne: "أنشئ واحداً مجاناً",
      alreadyHave: "لديك حساب بالفعل؟",
      signInLink: "سجّل دخولك",
      aiPowered: "إعلانات بالذكاء الاصطناعي",
      aiPoweredDesc: "أنشئ إعلانات مذهلة في ثوانٍ بـ Gemini AI",
      multiPlatform: "يدعم متعدد المنصات",
      multiPlatformDesc: "فيسبوك، انستغرام، جوجل، تيك توك والمزيد",
      performance: "نقاط الأداء",
      performanceDesc: "اعرف أي الإعلانات ستحقق نتائج قبل الإطلاق",
      joinMarketers: "انضم لأكثر من 10,000 مسوّق",
      generatingEveryday: "ينشئون إعلانات كل يوم",
      createsActuallyConvert: "أنشئ إعلانات",
      thatConvert: "تحقق نتائج فعلية",
      aiTrusted: "منصة إعلانية بالذكاء الاصطناعي يثق بها آلاف المسوّقين حول العالم.",
    },
    common: {
      loading: "جارٍ تحميل مساحة عملك…",
      go: "انتقل",
      failed: "فشل",
    },
  },
} as const;

export type Translations = typeof translations["en"];

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
  isRTL: false,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const stored = localStorage.getItem("adcreative-lang");
      return stored === "ar" ? "ar" : "en";
    } catch {
      return "en";
    }
  });

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    try { localStorage.setItem("adcreative-lang", newLang); } catch {}
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] as Translations, isRTL: lang === "ar" }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
